spring:
  profiles:
    include: secrets
  datasource:
#    url: "jdbc:mysql://localhost:3306/scorekeeper"
#    username: "root"
    url: "jdbc:mysql://awseb-e-pin3qirkwd-stack-awsebrdsdatabase-gbtif8ye7p3n.cufudecqblgj.us-east-2.rds.amazonaws.com:3306/scorekeeper"
    username: "Clayton"
    password: "Cc854285"
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

application:
  random:
    url: https://api.random.org/json-rpc/4/invoke
    key: ${secret.random.key}
