spring:
  profiles:
    include: secrets
  datasource:
    url: "jdbc:mysql://localhost:3306/scorekeeper"
    username: ${secrets.database.username}
    password: ${secrets.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: false

application:
  random:
    url: https://api.random.org/json-rpc/4/invoke
    key: ${secret.random.key}
